# Generated by Django 3.2.16 on 2022-11-13 03:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samcoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile', models.CharField(help_text='Give a name etc Sale man or manager, or Suppler', max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('img', models.ImageField(help_text='MAX 400kb', max_length=400, upload_to='img', verbose_name='Background Image')),
                ('img1', models.ImageField(blank=True, help_text='MAX 200kb', max_length=200, upload_to='img', verbose_name='Profile Image')),
                ('qualification', models.CharField(default='MCS', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=230),
        ),
        migrations.AlterField(
            model_name='contact',
            name='replay',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=250),
        ),
    ]
