# Generated by Django 3.2.16 on 2022-11-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samcoApp', '0002_auto_20221113_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(help_text='MAX 400kb', max_length=200, upload_to='img', verbose_name='Background Image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='img1',
            field=models.ImageField(blank=True, help_text='MAX 200kb', upload_to='img', verbose_name='Profile Image'),
        ),
    ]
