# Generated by Django 3.2.16 on 2022-11-15 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samcoApp', '0006_alter_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, upload_to='img')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='img',
        ),
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='service',
            name='author_img',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='samcoApp.author_img'),
            preserve_default=False,
        ),
    ]
