# Generated by Django 3.2.16 on 2022-11-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samcoApp', '0008_remove_author_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='author_img',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.DeleteModel(
            name='Author_Img',
        ),
    ]
