# Generated by Django 3.2.16 on 2022-11-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samcoApp', '0009_auto_20221115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='service',
            name='author_img',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
