# Generated by Django 3.2.16 on 2022-11-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samcoApp', '0011_contactu'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactu',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactu',
            name='phone',
            field=models.CharField(max_length=26),
        ),
    ]
